export const settingsConfig = {
  account: {
    marker: "[01] ACCOUNT OPS",
    badge: "IDENTITY CONTROL",
    headline: {
      line1: "ACCOUNT",
      line2: "CONTROL",
      line3: "PANEL",
    },
    description:
      "Everything tied to your OpenSolve identity: verification status, workspace roles, devices, and irreversible actions.",
    stats: {
      verification: "Verification",
      sessions: "Active sessions",
      twoFactor: "2FA status",
    },
    info: {
      marker: "[02]",
      title: "Identity & access",
      description: "Signal your verified email, workspace handle, and security posture.",
      emailLabel: "Email Address",
      verified: "Verified",
      unverified: "Not verified",
      resend: "Resend verification",
      usernameLabel: "Handle",
      roleLabel: "Account role",
      twoFactorLabel: "Two-factor auth",
      twoFactorEnabled: "Enabled",
      twoFactorDisabled: "Disabled",
      manageCta: "Manage in security",
      emailFootnote: "Official notices and recovery messages ship to this address.",
    },
    sessions: {
      marker: "[03]",
      title: "Active sessions",
      description: "Devices currently authenticated against your account. Revoke suspicious ones.",
      deviceUnknown: "Unknown device",
      lastActive: "Last active",
      revoke: "Revoke",
      current: "Current",
      empty: "No active sessions detected.",
      signOutAll: {
        title: "Sign out everywhere",
        description: "Terminate all active sessions across every device and reset tokens.",
        cta: "Sign out all",
      },
    },
    danger: {
      marker: "[04]",
      title: "Danger zone",
      description: "Irreversible actions that wipe your OpenSolve presence.",
      deleteTitle: "Delete account",
      deleteDescription:
        "This permanently removes submissions, proposals, analytics history, and your profile.",
      warningTitle: "Impacts",
      bullets: [
        "All submissions and analytics snapshots will be removed.",
        "Profile, teams, and proposal history will be erased.",
        "This cannot be undone; backups do not retain deleted identities.",
      ],
      passwordLabel: "Confirm with password",
      confirmCta: "Delete account",
      confirmHelper: "Enter your password to confirm.",
    },
  },
  profile: {
    marker: "[01] PROFILE OPS",
    badge: "PUBLIC SURFACE",
    headline: {
      line1: "PUBLISH",
      line2: "YOUR",
      line3: "SIGNAL",
    },
    description:
      "Tune how the community sees you across discussions, leaderboards, and problem trails. All fields sync live.",
    stats: {
      handle: "Handle",
      email: "Email",
      role: "Role",
    },
    avatar: {
      marker: "[02]",
      title: "Profile picture",
      helper: "Upload a new avatar (PNG or JPEG, max 2MB).",
      action: "Change avatar",
      uploading: "Uploading...",
    },
    form: {
      marker: "[03]",
      title: "Profile fields",
      description: "Keep metadata accurate for scoreboards, discussions, and team profiles.",
      nameLabel: "Display name",
      nameHelper: "This renders on leaderboards and discussion cards.",
      bioLabel: "Bio",
      bioHelper: "Brief description for your profile. Max 500 characters.",
      countryLabel: "Country",
      countryHelper: "Two-letter ISO code (e.g., US, CA, BG).",
      timezoneLabel: "Timezone",
      timezoneHelper: "IANA timezone identifier (e.g., Europe/Sofia).",
      avatarUrlLabel: "Avatar URL",
      avatarUrlHelper: "Direct link to your avatar image (optional).",
      saveCta: "Save changes",
      saved: "Saved successfully",
    },
  },
  security: {
    marker: "[01] SECURITY OPS",
    badge: "ZERO TRUST",
    headline: {
      line1: "HARDEN",
      line2: "YOUR",
      line3: "ACCOUNT",
    },
    description:
      "Rotate credentials, enforce 2FA, and keep recovery primitives nearby. All changes re-validate your session.",
    sections: {
      password: {
        marker: "[02]",
        title: "Change password",
        description: "Rotate credentials regularly to reduce credential reuse risk.",
        currentLabel: "Current password",
        newLabel: "New password",
        helper: "At least 8 characters with uppercase, lowercase, and numbers.",
        cta: "Update password",
        success: "Password updated",
      },
      email: {
        marker: "[03]",
        title: "Change email",
        description: "Update your primary identity and delivery address.",
        currentLabel: "Current email",
        newLabel: "New email",
        passwordLabel: "Confirm password",
        cta: "Update email",
        success: "Email updated",
      },
      twoFactor: {
        marker: "[04]",
        title: "Two-factor authentication",
        description: "Pair with an authenticator app to require OTP codes at login.",
        statusEnabled: "2FA enabled",
        statusDisabled: "2FA disabled",
        enableCta: "Enable 2FA",
        disableCta: "Disable 2FA",
        manualCodeLabel: "Manual entry code",
        confirmPasswordLabel: "Confirm your password",
        verificationCodeLabel: "Verification code",
        verificationPlaceholder: "000000",
        enableAction: "Enable 2FA",
        recoveryTitle: "Recovery codes",
        recoveryDescription: "Save these codes in a secure location.",
        copyAll: "Copy all",
        importantNote:
          "You’ll need these codes if you lose access to your authenticator device. Store them safely.",
        done: "Done",
      },
    },
  },
};

export type SettingsConfig = typeof settingsConfig;
